/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.conexao;
import static banco.conexao.statement;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }
     int cont;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblretire = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblretire.setText("jLabel1");
        lblretire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblretire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblretireMouseClicked(evt);
            }
        });
        getContentPane().add(lblretire, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 140, 200));

        lblsenha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblsenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsenha.setText("Senha");
        getContentPane().add(lblsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 90));

        jButton1.setText("Chamada de Senhas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
void retiradorImg() {
	ImageIcon imagem = new ImageIcon(principal.class.getResource("/img/retirar.png"));
	Image imag = imagem.getImage().getScaledInstance(lblretire.getWidth(), lblretire.getHeight(), Image.SCALE_DEFAULT);
	lblretire.setIcon(new ImageIcon(imag));
}
private void cadastraSenha(int numero) {
	conexao banco = new conexao();
	try {
		String sql = "INSERT INTO tb01_senhas\n" + "(tb01_numero, tb01_chamado)\n" + "VALUES (" + (numero + 1) + ", 'n')";
		banco.conectar();
		int rs = statement.executeUpdate(sql);
		System.out.println(sql);
		verBanco();
		banco.desconectar();
	} catch (Exception e) {
		System.out.println(e.getMessage());
	}
}
private void verBanco() {
	conexao banco = new conexao();
	try {
		String sql = "SELECT MAX(tb01_numero)AS max_numero from tb01_senhas";
		banco.conectar();
		ResultSet rs = statement.executeQuery(sql);
		if(rs.next()) {
			cont = rs.getInt("max_numero");
			lblsenha.setVisible(true);
			lblsenha.setText(String.valueOf(cont));
			System.out.println(cont);
		} else {
			System.out.println("Não foram encontrados resultados.");
		}
		banco.desconectar();
	} catch (Exception e) {
		System.out.println(e.getMessage());
	}
}
void atualiza() {
	verBanco();
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        retiradorImg();
        verBanco();
        lblsenha.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void lblretireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblretireMouseClicked
        cadastraSenha(cont);
    }//GEN-LAST:event_lblretireMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    retirada tela = new retirada();
    this.setVisible(false);
    tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblretire;
    private javax.swing.JLabel lblsenha;
    // End of variables declaration//GEN-END:variables
}
