/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.conexao;
import static banco.conexao.statement;
import java.sql.ResultSet;

/**
 *
 * @author pc
 */
public class retirada extends javax.swing.JFrame {

    /**
     * Creates new form retirada
     */
    public retirada() {
        initComponents();
    }
int cont;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
private void verBanco() {
	conexao banco = new conexao();
	try {
		String sql = "SELECT MIN(tb01_numero)AS min_numero from tb01_senhas";
		sql += "	WHERE tb01_chamado = 'n'";
		banco.conectar();
		ResultSet rs = statement.executeQuery(sql);
		if(rs.next()) {
			cont = rs.getInt("min_numero");
			lblsenha.setVisible(true);
			if(cont == 0) {
				lblsenha.setText("Sem senhas para serem chamadas");
			} else {
				lblsenha.setText(String.valueOf(cont));
			}
			System.out.println(cont);
		} else {
			System.out.println("Não foram encontrados resultados.");
		}
		banco.desconectar();
	} catch (Exception e) {
		System.out.println(e.getMessage());
	}
}
private void atualizaSenha() {
	conexao banco = new conexao();
	try {
		String sql = "UPDATE tb01_senhas\n" + "	SET\n" 
                        + "tb01_chamado='s'\n" 
                        + "WHERE tb01_numero=" + cont;
		banco.conectar();
		int rs = statement.executeUpdate(sql);
		verBanco();
		banco.desconectar();
	} catch (Exception e) {
		System.out.println(e.getMessage());
	}
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnchamada = new javax.swing.JButton();
        lblsenha = new javax.swing.JLabel();
        btnvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnchamada.setText("Chamar senha");
        btnchamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchamadaActionPerformed(evt);
            }
        });
        getContentPane().add(btnchamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblsenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblsenha.setText("Senha");
        getContentPane().add(lblsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 410, -1));

        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnchamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchamadaActionPerformed
        atualizaSenha();
    }//GEN-LAST:event_btnchamadaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblsenha.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        principal tela = new principal();
        this.setVisible(false);
        tela.setVisible(true);
    }//GEN-LAST:event_btnvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retirada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchamada;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel lblsenha;
    // End of variables declaration//GEN-END:variables
}
